### ISSUE TITLE
Can't find the pop rdi;ret; with ropr in LK01

### ISSUE THREAD

**Issue by Securee** [ptr-yudai/pawnyable#8]
Hi,
   I try to following the  LK01 to reproduce the  get root procedure.
   But when I use ropr to get rop gadget by: ropr vmlinux --noisy --nosys --nojop -R '^pop rdi.+ret;'
   the result is:
   
![image](https://github.com/ptr-yudai/pawnyable/assets/79675350/071a3ce3-09b1-479f-b7c5-68cfa11343b3)
the address 0xffffffff81f1f0e9 of curse in not correct.

I have no idear why the ropr can't find the correct address

**Comment by ptr-yudai** [comment]
You can use nouniq option to get other gadgets.
Please refer this PR for more details:
https://github.com/Ben-Lichtman/ropr/pull/13
